# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1765f3cd562bd12f233678c4c6a56b65131bf9f3c4b96bdc19b379ed2190e5f635ef06ef51984bc69122317c0339ea08a7389061b376a101d46dbaea81d44b64

test:
  secret_key_base: 69bf6da5a1e06cbfdacc7b565d035623de8418a6f646381426f5823c766fdae65bc17a9842108f6c150cdfad094d95c7085f41c7e5e71c2263e1650c7d1dd9ef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
